# Generated by Django 3.2.9 on 2022-07-28 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_number', models.IntegerField(primary_key=True, serialize=False)),
                ('room_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.roomtype')),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roomservice',
            name='room_name',
            field=models.ManyToManyField(related_name='services', to='api.RoomType'),
        ),
        migrations.DeleteModel(
            name='RoomVacancy',
        ),
        migrations.AlterField(
            model_name='booking',
            name='room_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.room'),
        ),
    ]
