# Generated by Django 3.2.9 on 2022-07-29 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_booking_total_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user_id',
            new_name='user',
        ),
    ]
