# Generated by Django 3.2.9 on 2022-07-29 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_user_id_booking_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='children_count',
            new_name='_children_count',
        ),
    ]
