# Generated by Django 3.2.9 on 2022-07-29 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_children_count_booking__children_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='_children_count',
            new_name='children_count',
        ),
    ]
