# Generated by Django 3.2.9 on 2022-07-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename__children_count_booking_children_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='_total_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
