# Generated by Django 3.2.9 on 2023-02-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220817_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='user_review',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='profile_picture',
            field=models.CharField(default='', max_length=40),
        ),
    ]
