# Generated by Django 3.2.9 on 2023-02-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_booking_user_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='user_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user_review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
