# Generated by Django 3.2.9 on 2023-03-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20230228_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='_total_cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
