# Generated by Django 3.2.9 on 2022-05-14 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomtype',
            old_name='desciption',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='roompicture',
            name='room_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_pictures', to='MainApp.roomtype'),
        ),
    ]
