# Generated by Django 3.2.9 on 2022-05-14 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_auto_20220514_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roompicture',
            old_name='image_address',
            new_name='picture_address',
        ),
    ]
