# Generated by Django 3.2.9 on 2022-05-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_rename_image_address_roompicture_picture_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='bed',
            field=models.CharField(default='bed', max_length=30),
            preserve_default=False,
        ),
    ]
